name: Multi Job Workflow

# Trigger the workflow based on a schedule
on:
  schedule:
    - cron: '10 13 * * *' # Runs daily at 14:10 CET (13:10 UTC)

jobs:
  setup-greeting:
    runs-on: ubuntu-latest

    env:
      GREETING: "Hello"
      NAME: "World"

    steps:
    - name: Set up greeting message
      run: |
        echo "Greeting: $GREETING, $NAME!"
        echo "Greeting message has been set up."

  print-greeting:
    runs-on: ubuntu-latest
    needs: setup-greeting

    steps:
    - name: Print Greeting with Secret
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }} # Use a secret stored in GitHub repository settings
      run: |
        echo "Using Environment Variables from setup-greeting:"
        echo "$GREETING, $NAME!"
        echo "Secret from settings: $MY_SECRET"
